/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.LoginController;
import Utility.UIData;
/**
 *
 * @author nabillaaura
 */
public class Login extends javax.swing.JFrame {

    private Controller.LoginController controller;
    
    public Login(LoginController controller) {
        this.controller = controller;
        initComponents();
    }
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3_MEmber = new javax.swing.JButton();
        jButton1_SignIn = new javax.swing.JButton();
        jButton2_Tutor = new javax.swing.JButton();
        jTextField2_Username = new javax.swing.JTextField();
        jPasswordField_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3_MEmber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Group 9 (2).png"))); // NOI18N
        jButton3_MEmber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_MEmberActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3_MEmber, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 90, 40));

        jButton1_SignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Group 10 (1).png"))); // NOI18N
        jButton1_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_SignInActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 341, 110, -1));

        jButton2_Tutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Group 9 (3).png"))); // NOI18N
        jButton2_Tutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_TutorActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2_Tutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 100, 40));

        jTextField2_Username.setBackground(new java.awt.Color(224, 187, 218));
        jTextField2_Username.setMaximumSize(new java.awt.Dimension(6, 22));
        jTextField2_Username.setOpaque(false);
        jPanel1.add(jTextField2_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 210, 300, 30));

        jPasswordField_password.setBackground(new java.awt.Color(224, 187, 218));
        jPasswordField_password.setMaximumSize(new java.awt.Dimension(6, 22));
        jPasswordField_password.setOpaque(false);
        jPasswordField_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 290, 300, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Sign in (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_SignInActionPerformed
        String username = jTextField2_Username.getText();
        String password = jPasswordField_password.getText();
        if(!username.isEmpty() && !password.isEmpty())
            controller.Login(username, password);
    }//GEN-LAST:event_jButton1_SignInActionPerformed

    private void jPasswordField_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_passwordActionPerformed

    private void jButton3_MEmberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_MEmberActionPerformed
       controller.MoveToSignUp(true);
    }//GEN-LAST:event_jButton3_MEmberActionPerformed

    private void jButton2_TutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_TutorActionPerformed
        controller.MoveToSignUp(false);
    }//GEN-LAST:event_jButton2_TutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_SignIn;
    private javax.swing.JButton jButton2_Tutor;
    private javax.swing.JButton jButton3_MEmber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JTextField jTextField2_Username;
    // End of variables declaration//GEN-END:variables
}
