/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author nabillaaura
 */
public class Pembayaran extends javax.swing.JFrame {

    /**
     * Creates new form Pembayaran
     */
    public Pembayaran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2_PaketNgambis = new javax.swing.JButton();
        jButton1_PaketSantai = new javax.swing.JButton();
        jButton4_SelectFile = new javax.swing.JButton();
        jButton5_Next = new javax.swing.JButton();
        jButton3_PaketLangganan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2_PaketNgambis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Group 13 (4).png"))); // NOI18N
        jPanel1.add(jButton2_PaketNgambis, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 160, 160));

        jButton1_PaketSantai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Group 8 (2).png"))); // NOI18N
        jPanel1.add(jButton1_PaketSantai, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 160, 170));

        jButton4_SelectFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Group 16.png"))); // NOI18N
        jPanel1.add(jButton4_SelectFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 130, 30));

        jButton5_Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Group 17 (1).png"))); // NOI18N
        jPanel1.add(jButton5_Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 100, 40));

        jButton3_PaketLangganan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Group 15.png"))); // NOI18N
        jPanel1.add(jButton3_PaketLangganan, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 150, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/pembayaran.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_PaketSantai;
    private javax.swing.JButton jButton2_PaketNgambis;
    private javax.swing.JButton jButton3_PaketLangganan;
    private javax.swing.JButton jButton4_SelectFile;
    private javax.swing.JButton jButton5_Next;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
