/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author nabillaaura
 */
public class Register_Tutor extends javax.swing.JFrame {

    /**
     * Creates new form Register_Tutor
     */
    public Register_Tutor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1_Username = new javax.swing.JTextField();
        jTextField4_RetypePassword = new javax.swing.JTextField();
        jTextField3_Password = new javax.swing.JTextField();
        jTextField2_NamaLengkapTutor = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2_CreateAccount = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1_NamaLengkap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1_Username.setBackground(new java.awt.Color(224, 187, 218));
        jTextField1_Username.setOpaque(false);
        jPanel1.add(jTextField1_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 290, 30));

        jTextField4_RetypePassword.setBackground(new java.awt.Color(224, 187, 218));
        jTextField4_RetypePassword.setOpaque(false);
        jPanel1.add(jTextField4_RetypePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 290, 30));

        jTextField3_Password.setBackground(new java.awt.Color(224, 187, 218));
        jTextField3_Password.setOpaque(false);
        jPanel1.add(jTextField3_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 290, 30));

        jTextField2_NamaLengkapTutor.setBackground(new java.awt.Color(224, 187, 218));
        jPanel1.add(jTextField2_NamaLengkapTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 290, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bank" }));
        jComboBox1.setToolTipText("");
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 90, 30));

        jButton2_CreateAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Group 14 (3).png"))); // NOI18N
        jPanel1.add(jButton2_CreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 140, 50));

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        jLabel1_NamaLengkap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Register Tutor (1).png"))); // NOI18N
        jLabel1_NamaLengkap.setText("jLabel1");
        jPanel1.add(jLabel1_NamaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Tutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Tutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Tutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Tutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Tutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2_CreateAccount;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1_NamaLengkap;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField1_Username;
    private javax.swing.JTextField jTextField2_NamaLengkapTutor;
    private javax.swing.JTextField jTextField3_Password;
    private javax.swing.JTextField jTextField4_RetypePassword;
    // End of variables declaration//GEN-END:variables
}
