/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author nabillaaura
 */
public class Register_Member extends javax.swing.JFrame {

    /**
     * Creates new form Register_Member
     */
    public Register_Member() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField2_UsernameMember = new javax.swing.JTextField();
        jTextField1_NamaLengkapMember = new javax.swing.JTextField();
        jTextField4_RetypePasswordMember = new javax.swing.JTextField();
        jTextField3_PasswordMember = new javax.swing.JTextField();
        jButton1_CreatAccountMember = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2_UsernameMember.setBackground(new java.awt.Color(224, 187, 218));
        jTextField2_UsernameMember.setOpaque(false);
        jPanel1.add(jTextField2_UsernameMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 270, 40));

        jTextField1_NamaLengkapMember.setBackground(new java.awt.Color(224, 187, 218));
        jTextField1_NamaLengkapMember.setOpaque(false);
        jPanel1.add(jTextField1_NamaLengkapMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 270, 30));

        jTextField4_RetypePasswordMember.setBackground(new java.awt.Color(224, 187, 218));
        jTextField4_RetypePasswordMember.setOpaque(false);
        jPanel1.add(jTextField4_RetypePasswordMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 270, 40));

        jTextField3_PasswordMember.setBackground(new java.awt.Color(224, 187, 218));
        jTextField3_PasswordMember.setOpaque(false);
        jPanel1.add(jTextField3_PasswordMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 270, 40));

        jButton1_CreatAccountMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Group 14 (3).png"))); // NOI18N
        jPanel1.add(jButton1_CreatAccountMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 140, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel2.setText("*Tuliskan beberapa hal tentang kamu!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, 20));

        jTextArea1.setBackground(new java.awt.Color(224, 187, 218));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 270, 80));

        jLabel1.setBackground(new java.awt.Color(224, 187, 218));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Register Member.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_CreatAccountMember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1_NamaLengkapMember;
    private javax.swing.JTextField jTextField2_UsernameMember;
    private javax.swing.JTextField jTextField3_PasswordMember;
    private javax.swing.JTextField jTextField4_RetypePasswordMember;
    // End of variables declaration//GEN-END:variables
}
